package hr.fer.oprpp1.hw02.prob1;

/**
 * @author Dominik
 * Custom runtime exception made to handle errors within Lexer work
 */
public class LexerException extends RuntimeException {

	/**
	 * generated by IDE
	 */
	private static final long serialVersionUID = -3799040841658945303L;

	/**
	 * Default constructor, calls this with generic message
	 */
	public LexerException() {
		this("Something was wrong with lexer handling.");
    }

    /** 
     * @param message Text to show user
     */
    public LexerException(String message) {
        super(message);
    }

}
